name: Test and Build for PR

on:
  pull_request:
    branches:
      - master
      - pre
      - dev

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Ejecutar linting
      - name: Run linting
        run: npm run lint

      # Paso 5: Ejecutar pruebas
      - name: Run tests
        run: npm run test

      # Paso 6: Verificar la construcción
      - name: Build project
        run: npm run build
